### ISSUE TITLE
HomeAssistant 2024.03.0 breaks plugin

### ISSUE THREAD

**Issue by LarsK1** [jaroschek/home-assistant-eaton-ups#12]
Hi,
after the latest update of HomeAssistant Core to 2024.03.0 the plugin is broken. 

`Setup failed for custom integration 'eaton_ups': Requirements for eaton_ups not found: ['pysnmplib==5.0.21']`

Any idea why?

Thanks for any help,
Lars

**Comment by jaroschek** [comment]
As the core snmp integration (https://github.com/home-assistant/core/tree/dev/homeassistant/components/snmp) was migrated to `pysnmp-lextudio==6.0.2` I will have to migrate my snmp integration(s) too.

I'm working on it right now.

**Comment by jaroschek** [comment]
I have released version `1.2.0` to address the recent incompatibility.

Please give it a try: https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.2.0

**Comment by roschi02** [comment]
works perfectly.

**Comment by LarsK1** [comment]
Yep, for me as well. Thanks for the quick fixing!

**Comment by jaroschek** [comment]
A quick update: I observed some kind of memory leak using the updated integration. This might be caused by the usage of asyncio (using async and await) already in the updated library `pysnmp-lextudio==6.0.2`. 

As the former synchronous callbacks are no longer available I tried an other solution by using an older version of the library `pysnmp-lextudio==5.0.34`.

Therefore I made another release package based on the previous solution: https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.1.3

**Comment by roschi02** [comment]
1.1.3 also works for me but hacs sees 1.2 as a newer version and wants to update, just something to keep in mind.

**Comment by jaroschek** [comment]
Okay. I flagged `1.1.3` as `latest`.

I first should have made this change by just switching to the new library without upgrading the requirement to version `6.0.2`. Would have been much faster. Hope this works for some time... until I can figure out the memory leak I observed.

**Comment by roschi02** [comment]
Hacs is stil thinking 1.2 is the latest version, maybe hacs needs a little bit more time to realise or is not accepting the latest flag.

**Comment by LarsK1** [comment]
Hi,
I "downgraded" to 1.1.3, but it keeps on automatically upgrading to 1.2.0. Can you please release an 1.2.1, so we can really "upgrade"?

**Comment by jaroschek** [comment]
I have just removed the Release 1.2.0 now. So 1.1.3 is now the latest one.

1.2.x need some work to solve the observed memory leak after switching to async requests.

**Comment by LarsK1** [comment]
Now I'm getting:
```
Unexpected error fetching eaton_ups data: 'coroutine' object is not an iterator
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eaton_ups/coordinator.py", line 134, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eaton_ups/coordinator.py", line 67, in _update_data
    data = self._api.get(
           ^^^^^^^^^^^^^^
  File "/config/custom_components/eaton_ups/api.py", line 87, in get
    return __class__.fetch(iterator, 1)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eaton_ups/api.py", line 138, in fetch
    error_indication, error_status, error_index, var_binds = next(iterator)
                                                             ^^^^^^^^^^^^^^
TypeError: 'coroutine' object is not an iterator
```

**Comment by xoatrash** [comment]
Yes, I can confirm the memory issue with 1.2.  i took me days to find out whats is causing the issue.

**Comment by xoatrash** [comment]
Is there a working version for now? 1.1.3 also does not wirk for me. It wont load the config.

**Comment by jaroschek** [comment]
@roschi02 I have updated the integration to use the same version of `pysnmp` as the snmp component of Home Assistant.

You could try the new release 1.2.0.

**Comment by LarsK1** [comment]
@jaroschek 
thanks for the update. Now it work's reliable (at least for me and now :))
