### ISSUE TITLE
Missing label on setup wizard

### ISSUE THREAD

**Issue by reedy** [jaroschek/home-assistant-eaton-ups#2]
![Screenshot 2024-01-04 at 01 50 38](https://github.com/jaroschek/home-assistant-eaton-ups/assets/67615/704bfe74-e81d-4ca9-b7ec-c60ce738775c)

What is the first field supposed to be? The "name" for the device?

Can we get a label added to make it obvious?

Thanks!

**Comment by colindawson** [comment]
Yes this field is for the name of the device, I just installed and got it working with my 5PX.     This plugin is a great addition, as I don't need to setup a NUT server to in addition to my UPS network setup.   Love it.

**Comment by jaroschek** [comment]
I now removed the field for the custom title of the config entry. Instead the product name of the configred device will be fetched and used as title of the config entry.

See https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.1.0

**Comment by jaroschek** [comment]
As the automatic detection of product name and serial number was not reliable, I reverted the changes to the config flow to manually enter the name of the config entry.

... and I added the missing label of the name inout field too:
<img width="369" alt="Bildschirmfoto 2024-02-08 um 06 59 55" src="https://github.com/jaroschek/home-assistant-eaton-ups/assets/470290/0a651807-2220-4a40-b448-b0f16ff953db">
