### ISSUE TITLE
Error adding two ups eaton

### ISSUE THREAD

**Issue by fapgomes** [jaroschek/home-assistant-eaton-ups#37]
Hi,

 When I try to add two UPSs in the second I have this error:

```
024-10-22 16:55:28.489 ERROR (MainThread) [homeassistant.components.sensor] Platform eaton_ups does not generate unique IDs. ID eaton_ups_Eaton 9PX 11000i 3:1_1.3.6.1.4.1.534.1.3.4.1.2.3 already exists - ignoring sensor.eaton_9px_11000i_3_1_input_none_voltage_3
2024-10-22 16:55:28.489 ERROR (MainThread) [homeassistant.components.sensor] Platform eaton_ups does not generate unique IDs. ID eaton_ups_Eaton 9PX 11000i 3:1_1.3.6.1.4.1.534.1.4.4.1.2.1 already exists - ignoring sensor.eaton_9px_11000i_3_1_output_none_voltage
2024-10-22 16:55:28.489 ERROR (MainThread) [homeassistant.components.sensor] Platform eaton_ups does not generate unique IDs. ID eaton_ups_Eaton 9PX 11000i 3:1_1.3.6.1.4.1.534.1.4.4.1.3.1 already exists - ignoring sensor.eaton_9px_11000i_3_1_output_none_current
2024-10-22 16:55:28.489 ERROR (MainThread) [homeassistant.components.sensor] Platform eaton_ups does not generate unique IDs. ID eaton_ups_Eaton 9PX 11000i 3:1_1.3.6.1.4.1.534.1.4.4.1.4.1 already exists - ignoring sensor.eaton_9px_11000i_3_1_output_none_watts
2024-10-22 16:55:28.489 ERROR (MainThread) [homeassistant.components.sensor] Platform eaton_ups does not generate unique IDs. ID eaton_ups_Eaton 9PX 11000i 3:1_1.3.6.1.4.1.534.1.4.4.1.8.1 already exists - ignoring sensor.eaton_9px_11000i_3_1_output_none_load

```

Best Regards,

**Comment by jaroschek** [comment]
@fapgomes It seems your devices don't provide a serial number. And as I implemented a fallback to get at least some kind of identifier for #19 its using your devices name `Eaton 9PX 11000i 3:1` as identifier to create the unique ids. And as all your devices are of the same model, this leads to identical unique ids.

I'm currently using an 9PX 3000i RT 3U with an Gigabit Network Card (M2) that provides th serial number. So in my case a unique entity id will look like this: `eaton_ups_GA15L34063_1.3.6.1.4.1.534.1.2.8.0`

To solve your problem I will have to introduce some other kind of unique identifier as the serial number does not seem to be available. Or can you find out if your devices provide a serial number on a different OID?

Using the serial number has one bug advantage: You can remove and add your devices through this integration and you could even change the network interface or SNMP configuration. As the serial number of a devices stays the same all entities keep their history.

**Comment by jaroschek** [comment]
@fapgomes May I ask what SNMP version and community you are using and what network interface card is installed in your devices?

**Comment by jaroschek** [comment]
@fapgomes As I was writing and reading OID definitions from Eaton for their UPS devices I stumbled over some different OIDs defined in their XUPS documents.

So I added alternate OIDs for firmware, product name and serial number to fetch the values from.

The changes are available as a pre-release: https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.2.3-rc1

Please give it a try. Would be great, if this would solve the issues caused by missing serial numbers.

**Comment by jaroschek** [comment]
@fapgomes As a last try I have now even changed the previous fallback logic for the unique device identifier to use the configured host of the config entry.

The change is available as a new pre-release: https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.2.3-rc2

Now if there is no serial number available through any of the known 2 OIDs the unique identifier will use the host (eg. ip address) of the configure device to create unique entity ids like this: `eaton_ups_10.0.1.30_1.3.6.1.4.1.534.1.2.8.0`

This way your devices will be identified by their configured hosts. But if you change the host, you will loose the history of the device entities.

**Comment by fapgomes** [comment]
> @fapgomes May I ask what SNMP version and community you are using and what network interface card is installed in your devices?

I have changed to the v1 public, and the problem is the same.

> The change is available as a new pre-release: https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.2.3-rc2

It worked!

![Screenshot_20241023_105321](https://github.com/user-attachments/assets/eeffc1de-65ac-4bae-8cf2-a6ab79783f5e)

Best Regards,

**Comment by jaroschek** [comment]
@fapgomes I'm glad it worked!

I have now created a final public release for these changes: https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.2.3
